### **Въпрос 1**

In [3]:
import numpy as np

adj_matrix = np.array([
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 0]
])
print(adj_matrix)

[[0 1 1]
 [1 0 1]
 [1 1 0]]


### **Въпрос 2**

In [4]:
import numpy as np

adj_matrix = np.array([
    [0, 1, 1],
    [0, 0, 1],
    [0, 0, 0]
])
print(adj_matrix)

[[0 1 1]
 [0 0 1]
 [0 0 0]]


### **Зад. 1 Depth First Search**

#### *Eфективна реализация:*

In [15]:
import numpy as np

graph = np.array([
    [0, 1, 1, 0, 0], 
    [1, 0, 0, 1, 0],  
    [1, 0, 0, 1, 1],  
    [0, 1, 1, 0, 1],  
    [0, 0, 1, 1, 0]  
])

def dfs(graph, start):
    visited = set()    # защо set()?
    stack = [start]         

    while stack:
        node = stack.pop()   

        if node not in visited:
            visited.add(node)
            print(node, end=" ")

            # какво гарантира обратният ред?
            for neighbor in reversed(range(len(graph[node]))): 
                if graph[node][neighbor] == 1 and neighbor not in visited:
                    stack.append(neighbor)  # push в стека

dfs(graph, 0)

0 1 3 2 4 

- При $set()$ имаме $O(1)$ за проверка дали елемент е в мн-вото и няма дублиране на елементи по дефиниция;
- Гарантира, че по-малките индекси се обработват първо т.е. първо навлизаме дълбоко.

#### *Неефективна реализация:*

In [13]:
import numpy as np

graph = np.array([
    [0, 1, 1, 0, 0], 
    [1, 0, 0, 1, 0],  
    [1, 0, 0, 1, 1],  
    [0, 1, 1, 0, 1],  
    [0, 0, 1, 1, 0]  
])

def dfs(graph, start):
    visited = set()          
    stack = np.array([start]) 

    while stack.size > 0:
        node = stack[-1]    
        stack = stack[:-1]   

        if node not in visited:
            visited.add(node)
            print(node, end=" ")

            for neighbor in reversed(range(len(graph[node]))): 
                if graph[node][neighbor] == 1 and neighbor not in visited:
                    stack = np.append(stack, neighbor) 
dfs(graph, 0)

0 1 3 2 4 

### **Зад 2. Breadth First Search**

### *Ефективна реализация:*

In [6]:
import numpy as np
from collections import deque

graph = np.array([
    [0, 1, 1, 0, 0],
    [1, 0, 0, 1, 0],
    [1, 0, 0, 1, 1],
    [0, 1, 1, 0, 1],
    [0, 0, 1, 1, 0]
])

def bfs(graph, start):
    visited = set()        
    queue = deque([start])  # защо deque()?
    visited.add(start)

    while queue:
        node = queue.popleft()   
        print(node, end=" ")     

        for neighbor in range(len(graph[node])):
            if graph[node][neighbor] == 1 and neighbor not in visited:
                visited.add(neighbor)
                queue.append(neighbor)

bfs(graph, 0)

0 1 2 3 4 

- При $deque()$ позволява бързо добавяне и премахване от двете страни - използваме $popleft()$, за да вземем елемента отпред.

#### *Неефетивна реализация:*

In [14]:
import numpy as np

graph = np.array([
    [0, 1, 1, 0, 0],
    [1, 0, 0, 1, 0],
    [1, 0, 0, 1, 1],
    [0, 1, 1, 0, 1],
    [0, 0, 1, 1, 0]
])

def bfs(graph, start):
    visited = set()             
    queue = np.array([start])  
    visited.add(start)

    while queue.size > 0:
        node = queue[0]         
        queue = queue[1:]      
        print(node, end=" ")

        for neighbor in range(len(graph[node])):
            if graph[node][neighbor] == 1 and neighbor not in visited:
                visited.add(neighbor)
                queue = np.append(queue, neighbor) 

bfs(graph, 0)

0 1 2 3 4 

### **Зад 3. Prim's Algortihm**

In [16]:
graph = [
    [0, 2, 0, 6, 0],
    [2, 0, 3, 8, 5],
    [0, 3, 0, 0, 7],
    [6, 8, 0, 0, 9],
    [0, 5, 7, 9, 0]
]

def prim_mst(graph):
    V = len(graph)
    selected = [False] * V # булев масив, който показва кои върхове вече са включени в MST
    selected[0] = True # (!) не е False
    mst_edges = [] # съхранява ребрата на MST като списък от тройки

    for _ in range(V - 1): # защо V-1?
        minimum = float('inf') # (!) не е -inf
        x = y = 0 # пазим върховете на избраното ребро.
        for i in range(V):
            if selected[i]: # ако i вече е включен в MST, разглеждаме неговите съседни върхове.
                for j in range(V): # ако j не е включен в MST и има ребро, го разглеждаме.
                    if not selected[j] and graph[i][j] != 0: # (!) не е == 0
                        if graph[i][j] < minimum: # (!) не е > minimum
                            minimum = graph[i][j]
                            x, y = i, j
        mst_edges.append((x, y, graph[x][y]))
        selected[y] = True # (!) не е selected[x]

    return mst_edges

print(prim_mst(graph))

[(0, 1, 2), (1, 2, 3), (1, 4, 5), (0, 3, 6)]


- Дърво с $V$ върха има $V-1$ ребра - по дефиниция.

### **Зад 4. Kruskal's Algorithm**

In [1]:
graph = [
    [0, 2, 0, 6, 0],
    [2, 0, 3, 8, 5],
    [0, 3, 0, 0, 7],
    [6, 8, 0, 0, 9],
    [0, 5, 7, 9, 0]
]
# parent е масив, който следи за всеки връх кой е представителят на множеството му
def find(parent, i):
    if parent[i] != i:
        parent[i] = find(parent, parent[i])
    return parent[i] # (!) връща родителя, не самия връх

def union(parent, i, j): # намират корените на множествата
    pi = find(parent, i) # (!) i и j са разменени
    pj = find(parent, j)
    if pi != pj:
        parent[pi] = pj
        return True # връща True, ако е извършено обединение т.е. реброто може да се добави в MST
    return False    # връща False, ако би се образувал цикъл

def kruskal_mst(graph): # защо обхождаме горната триъгълна част на матрицата?
    V = len(graph)
    edges = []
    for i in range(V):
        for j in range(i, V):
            if graph[i][j] != 0: # (!) не е ==0
                edges.append((graph[i][j], i, j))
    edges.sort() # сортираме по тегло, защото Kruskal започва с най-евтините ребра

    parent = list(range((V)))
    mst_edges = []

    for weight, u, v in edges:
        if union(parent, u, v): # ако е True, добавяме ръба към MST
            mst_edges.append((u, v, weight))
            if len(mst_edges) == V - 1: # (!) не са V на брой ребра
                break

    return mst_edges

print(kruskal_mst(graph))

[(0, 1, 2), (1, 2, 3), (1, 4, 5), (0, 3, 6)]


- Обхождаме горната триъгълна част на матрицата, защото графът е неориентиран ($i$ -> $j$ и $j$ -> $i$ са едно и също).

### **Зад 5. Dijkstra's Algorithm**

In [2]:
import heapq

def dijkstra_heap(graph, source):
    n = len(graph)
    dist = [float('inf')] * n # най-краткото разстояние от src до връх i
    dist[source] = 0          # първоначално всичко е inf, освен началния връх
    visited = [False] * n     # дали връх i вече е обработен окончателно

    heap = [(0, source)]

    while heap:
        current_dist, u = heapq.heappop(heap) # изваждаме върха с най-малко разстояние

        if visited[u]:  # ако върхът вече е обработен - пропускаме
            continue
        visited[u] = True

        for v in range(n):
            weight = graph[u][v]
            if weight > 0 and not visited[v]: # ако има ребро и v не е посетен
                new_dist = current_dist + weight # изчисляваме новия потенциално по-кратък път
                if new_dist < dist[v]:  # ако новият път е по-кратък - обновяваме разстоянието
                    dist[v] = new_dist
                    heapq.heappush(heap, (new_dist, v)) # добавяме новата двойка в heap-а

    return dist


graph = [
    [0, 4, 0, 0, 0, 0, 0, 8, 0],
    [4, 0, 8, 0, 0, 0, 0, 11, 0],
    [0, 8, 0, 7, 0, 4, 0, 0, 2],
    [0, 0, 7, 0, 9, 14, 0, 0, 0],
    [0, 0, 0, 9, 0, 10, 0, 0, 0],
    [0, 0, 4, 14, 10, 0, 2, 0, 0],
    [0, 0, 0, 0, 0, 2, 0, 1, 6],
    [8, 11, 0, 0, 0, 0, 1, 0, 7],
    [0, 0, 2, 0, 0, 0, 6, 7, 0]
]

print(dijkstra_heap(graph, 0))

[0, 4, 12, 19, 21, 11, 9, 8, 14]


### **Зад 6. Uniform Cost Search**

In [10]:
import heapq

def ucs(graph, start):
    n = len(graph)
    visited = [False] * n
    dist = [float('inf')] * n # текущият известен най-кратък „cost“ от start до връх i
    dist[start] = 0
    
    heap = [(0, start)]
    
    while heap:
        cost, u = heapq.heappop(heap) # взимаме върха u с най-малък текущ cost - Min Heap гарантира, че 
                                      # винаги работим с най-евтиния път на този етап
        if visited[u]:
            continue
        visited[u] = True
        
        for v in range(n):
            if graph[u][v] > 0 and not visited[v]: # (!) не е visited[u]
                new_cost = cost + graph[u][v] # (!) не е минус, защото добавяме текущата цена cost до u към теглото на реброто u -> v
                if new_cost < dist[v]:
                    dist[v] = new_cost # ако намерим по-кратък път до v, обновяваме dist[v]
                    heapq.heappush(heap, (new_cost, v)) # (!) не е (v, new_cost)
    
    return dist

graph = [
    [0, 4, 0, 0, 0, 0, 0, 8, 0],
    [4, 0, 8, 0, 0, 0, 0, 11, 0],
    [0, 8, 0, 7, 0, 4, 0, 0, 2],
    [0, 0, 7, 0, 9, 14, 0, 0, 0],
    [0, 0, 0, 9, 0, 10, 0, 0, 0],
    [0, 0, 4, 14, 10, 0, 2, 0, 0],
    [0, 0, 0, 0, 0, 2, 0, 1, 6],
    [8, 11, 0, 0, 0, 0, 1, 0, 7],
    [0, 0, 2, 0, 0, 0, 6, 7, 0]
]

print(ucs(graph, 0))

[0, 4, 12, 19, 21, 11, 9, 8, 14]


### **Зад 7. A\* Search in Minecraft**

#### **Отговор: Път B**

In [11]:
import heapq

def astar(grid, start, goal, heuristic):
    rows, cols = len(grid), len(grid[0])
    open_set = [(heuristic(start, goal), 0, start, [start])]
    visited = set()

    while open_set:
        f, g, node, path = heapq.heappop(open_set)
        if node in visited:
            continue
        visited.add(node)

        if node == goal:
            return path, g

        x, y = node
        for dx, dy in [(1,0), (-1,0), (0,1), (0,-1)]:  # 4-way movement
            nx, ny = x + dx, y + dy
            if 0 <= nx < rows and 0 <= ny < cols and grid[nx][ny] < 999:
                if (nx, ny) not in visited:
                    new_g = g + grid[nx][ny]
                    new_f = new_g + heuristic((nx, ny), goal)
                    heapq.heappush(open_set, (new_f, new_g, (nx, ny), path + [(nx, ny)]))

    return None, float("inf")


def heuristic(a, b):
    return abs(a[0] - b[0]) + abs(a[1] - b[1])

grid = [
        [ 1,   1,   1,   1,   0,   1,   1,   1,    1,  1,  1],
        [ 8,  999,  8,  999,  1,  999,  1,  999, 999, 999, 8],
        [ 8,  999,  8,  999, 999, 999,  1,   1,    1, 999, 8],
        [ 8,  999,  8,  999,  1,  999, 999, 999,   1, 999, 8],
        [ 8,  999,  8,  999, 999, 999,  1,   1,    1, 999, 8],
        [ 8,  999,  8,  999,  1,  999,  1,  999, 999, 999, 8],
        [ 8,  999,  8,  999,  1,  999,  1,   24,   1, 999, 8], 
        [ 8,  999,  8,  999,  1,  999, 999, 999,  16, 999, 8],
        [ 1,   1,   1,   1 ,  0,   1,   1,   16,   1,  1,  1],
]

start = (7, 4)   
goal = (0, 4)    

path, cost = astar(grid, start, goal, heuristic)
print(path, cost)

[(7, 4), (8, 4), (8, 3), (8, 2), (7, 2), (6, 2), (5, 2), (4, 2), (3, 2), (2, 2), (1, 2), (0, 2), (0, 3), (0, 4)] 60


### **Зад 8. Havel-Hakimi's Algorithm**

- Алгоритъмът проверява дали дадена последователност от естествени числа може да бъде степенна последователност на прост неориентиран граф (т.е. дали съществува граф с тези степени на върховете) Тук наричаме такава последователност `графична`.
- Алгоритъм:
    - Вземи последователността на степени $d = [d_1, d_2, \dots, d_n]$ и я подреди в низходящ ред;
    - Докато последователността не е празна:
        - Ако първото число $d_1 = 0$, и всички останали също са $0$, последователността е графична и спираме;
        - Изваждаме първото число $d_1$ от последователността;
        - Намаляваме с $1$ следващите $d_1$ числа в списъка (свързваме върха с $d_1$ други върха);
        - Ако някое число стане отрицателно, последователността не е графична и спираме;
        - Подреждаме останалата последователност в низходящ ред и повтаряме.
- Крайният резултат:
    - Ако процесът завърши успешно без отрицателни числа, последователността е графична;
    - Ако се появи отрицателно число, последователността не може да се реализира като степени на върхове на граф.

In [12]:
import numpy as np

def havel_hakimi(sequence):
    seq = np.array(sequence, dtype=int)

    while True:
        seq = seq[seq > 0]            # махаме нулите
        if len(seq) == 0:
            return True               # всички нули, значи графична
        
        seq = np.sort(seq)[::-1]      # сортираме в низходящ ред
        d = seq[0]                    # взимаме най-голямата степен
        seq = seq[1:]                 # махаме я

        if d > len(seq):
            return False              # не може да се свърже с толкова върхове

        seq[:d] -= 1                  # намаляваме следващите d елемента
        if np.any(seq < 0):
            return False              # отрицателна стойност, значи невалидна

print(havel_hakimi([3, 3, 2, 2, 2]))   
print(havel_hakimi([4, 2, 0, 1, 5]))   
print(havel_hakimi([1, 1]))  

True
False
True


### **Зад 9. Проверка за двуделност**

[**ЛИНК**](https://leetcode.com/problems/is-graph-bipartite/)

In [14]:
from typing import List

class Solution:
    def isBipartite(self, graph: List[List[int]]) -> bool:
        n = len(graph)
        color = [-1] * n # всички върхове започват непосетени

        def dfs(node: int, c: int) -> bool:
            color[node] = c # оцветяваме текущия връх
            for nei in graph[node]: # за всеки съсед
                if color[nei] == -1:
                    if not dfs(nei, 1 - c): # ако е непосетен -> рекурсивно извикваме DFS с противоположен цвят (1 - c)
                        return False
                elif color[nei] == color[node]: # ако вече е оцветен и има същия цвят -> връщаме False
                    return False
            return True
        
        for i in range(n):
            if color[i] == -1: # проверяваме всеки непосетен връх като начална точка за DFS
                               # това покрива и случаите с граф, състоящ се от няколко компоненти
                if not dfs(i, 0):
                    return False
        return True

### **Зад 10. Yen's Algorithm**

- Намиране на $K$ най-кратки пътища в граф.

``` java
package Algorithms;

import Graph.Edge;
import Graph.Graph;
import Graph.Path;
import Graph.Vertex;

import java.util.*;
import java.util.stream.Collectors;

public class Yen {
    private final Graph graph;
    private final Dijkstra dijkstra;

    public Yen(Graph graph) {
        this.graph = graph;
        this.dijkstra = new Dijkstra(graph);
    }

    public List<Path> calculate(Vertex source, Vertex target, int k) {
        List<Path> paths = new ArrayList<>(); // списък с намерените пътища.
        Path shortestPath = dijkstra.getShortestPath(source, target, null); // първо се намира най-краткият път с Dijkstra
        if (shortestPath == null) {
            return paths;
        }

        paths.add(shortestPath); // добавяме първия път и създаваме exclusionCandidates - ребрата, които вече са използвани, за да не се повтарят
        Set<Edge> exclusionCandidates = new HashSet<>(shortestPath.getEdges(graph));

        for (int i = 1; i < k; i++) { // търси следващият кратък път
            Path minPath = findNextShortestPath(paths.get(i - 1), source, target, exclusionCandidates);
            if (minPath == null) {
                break;
            }
            paths.add(minPath);
            exclusionCandidates.addAll(minPath.getEdges(graph));
        }
        return paths;
        // след първия кратък път, всяка нова итерация търси следващия минимален път, като избягва вече използвани комбинации от ребра
    }

    private Path findNextShortestPath(Path previousPath, Vertex source, Vertex target, Set<Edge> exclusionCandidates) {
        Path minPath = null;
        List<Vertex> vertices = previousPath.getVertices();
        // взимаме последния намерен път и разглеждаме всеки връх като потенциален корен за нов път
        for (int j = 0; j < vertices.size() - 1; j++) {
            Vertex root = vertices.get(j);
            Path spurPath = buildSpurPath(source, root, target, exclusionCandidates); // за всеки корен се изгражда разклонение до целта, като се избягват ребрата в exclusionCandidates
            if (spurPath == null || !spurPath.getVertices().contains(target)) {
                continue;
            }
            if (minPath == null || spurPath.getWeight() < minPath.getWeight()) {
                minPath = spurPath;
            } // ако разклонението е валиден и по-кратък от текущия minPath -> обновяваме minPath
        }
        return minPath; // връща се най-краткият валиден spur path за тази итерация
    }

    private Path buildSpurPath(Vertex source, Vertex root, Vertex target, Set<Edge> exclusionCandidates) {
        Path rootPath = dijkstra.getShortestPath(source, root, null); // най-краткият път от началото до root
        Set<Edge> excludedEdgesFromRoot = exclusionCandidates.stream() 
                .filter(edge -> edge.source().equals(root))
                .collect(Collectors.toSet()); // избрани ребра, които трябва да се избегнат при строене на spur path

        Path spur = dijkstra.getShortestPath(root, target, excludedEdgesFromRoot); // краткият път от root до целта, без да се използват изброените ребра
        if (spur == null) {
            return null;
        }
        return rootPath.join(spur, true); // съединяват rootPath + spur т.е. получаваме нов потенциален кратък път
    }
}
```